apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-deployment
  labels:
    app: mealie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9000"
    spec:
      containers:
        - name: mealie
          image: mealie-instrumented:latest
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /api/health
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
